<template>	<view>		<u-navbar title="修改登录密码"></u-navbar>
		<u-toast ref="uToast" />		<view style="color: #000000; height: 100rpx;">			<u-row gutter="12" style="margin-top:30rpx;background-color: #FFFFFF;">				<u-col span="1"></u-col>				<label v-model="mobile" style="font-size: 40rpx; margin-top:10rpx;margin-bottom:5rpx ; background-color: #FFFFFF;">{{ mobile }}</label>				<u-col span="1"></u-col>			</u-row>			<u-row gutter="12" style="margin-top:1rpx;background-color: #FFFFFF;">				<u-col span="1"></u-col>				<u-input v-model="code" style="background-color: #FFFFFF;" placeholder="请输入验证码" maxlength="6"></u-input>				<u-verification-code span="5" :seconds="seconds" @end="end" @start="start" ref="uCode" @change="codeChange"></u-verification-code>				<u-button @tap="getCode">{{ tips }}</u-button>				<u-col span="1"></u-col>			</u-row>			<u-row gutter="12" style="margin-top:1rpx;background-color: #FFFFFF;">				<u-col span="1"></u-col>				<u-input v-model="password1" type="password" password-icon="true" placeholder="请输入6到20位数字、字母密码" maxlength="20" />				<u-col span="1"></u-col>			</u-row>			<u-row gutter="12" style="margin-top:1rpx;background-color: #FFFFFF;">				<u-col span="1"></u-col>				<u-input v-model="password2" type="password" password-icon="true" placeholder="确认密码" maxlength="20" />				<u-col span="1"></u-col>			</u-row>			<u-row gutter="12">				<u-col span="1"></u-col>				<u-col span="10" style="padding-top: 180upx;"><u-button type="success" shape="circle" @click="nextclik">保存修改</u-button></u-col>				<u-col span="1"></u-col>			</u-row>		</view>	</view></template><script>import { getSendsms } from '@/api/feedBackList.js';import { changeLoginPassWord } from '@/api/feedBackList.js';import { setStores, getStores, isEmpty, isPoneAvailable, cutChinese } from '@/common/utils.js';import md5Libs from "uview-ui/libs/function/md5";import { login, regist, smsSend, smsLogin } from '@/api/login.js';import wechat from '@/common/wechat.js';var wx = require('jweixin-module');import Vue from 'vue';export default {	data() {		return {			tips: '',			// refCode: null,			seconds: 60,			yzm: '获取验证码',			mobile: '',			code: '',			password1: '',			password2: ''		};	},	methods: {		codeChange(text) {			this.tips = text;		},		getCode() {			if (this.$refs.uCode.canGetCode) {				// 模拟向后端请求验证码				uni.showLoading({					title: '正在获取验证码'				});				let $this = this;				let param = {					type: '6',					mobile: this.mobile,					apptype: '23'				};				console.log(param);				getSendsms(param).then(res => {					//只处理 code=1的结果  code等于其他会自动弹出错误提示框					console.log(res);					if ((res.code == 1)) {											setTimeout(() => {							uni.hideLoading();							// 这里此提示会被this.start()方法中的提示覆盖							this.$u.toast('验证码已发送');							// 通知验证码组件内部开始倒计时							this.$refs.uCode.start();						}, 2000);					}				});			}		},
		showToast() {
						this.$refs.uToast.show({
							title: '修改成功',
							type: 'success',
							url: '/pages/login'
						})
					},		nextclik() {
						let user = getStores('users');			this.mobile = user.mobile;			console.log(this.mobile);			if (this.password1 != this.password2) {
				// uni.showToast({				// 		icon:'none',				// 		title:'请确认两次密码输入一致'				// 	})
					
						this.$refs.uToast.show({
						title: '请确认两次密码输入一致',
						type: 'success',

					})				return;			}			let param = {				yzm: this.code,				mobile: this.mobile,				password: md5Libs.md5(this.password1)			};						changeLoginPassWord(param).then(res => {				//只处理 code=1的结果  code等于其他会自动弹出错误提示框				console.log(res);				if (res.code == 1) {					// this.$router.go(-1);//返回上一层
					this.showToast()				}			});		},		onLoad: function(e) {			//页面创建完毕 调用的函数			this.$this = this;			let user = getStores('users');			this.mobile = user.mobile;			console.log(this.mobile);		}	}};</script><style></style>
